### ISSUE TITLE
Error when run and crashing homebridge

### ISSUE THREAD

**Issue by livefeed** [joe-ng/homebridge-dyson-link#92] opened 2019-07-30 19:42 UTC
Getting this error

[7/30/2019, 4:01:28 PM] [DysonPlatform] Use device password from account
[7/30/2019, 4:01:28 PM] [DysonPlatform] Dyson IP:10.0.1.161 Serial Number:DYSON-NM7-US-XXXXXXX-475
[7/30/2019, 4:01:28 PM] [DysonPlatform] Device serial number format valids
[7/30/2019, 4:01:28 PM] [DysonPlatform] Device cached. Try to update this
[7/30/2019, 4:01:28 PM] [DysonPlatform] Init Sensor for Dyson
[7/30/2019, 4:01:28 PM] [DysonPlatform] Init Fan State for Dyson
[7/30/2019, 4:01:28 PM] [DysonPlatform] Auto switch found. Remove this now
[7/30/2019, 4:01:28 PM] [DysonPlatform] Night mode button is added
HAP Warning: Characteristic 000000BF-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000B7-0000-1000-8000-0026BB765291. Adding anyway.
[7/30/2019, 4:01:28 PM] [DysonPlatform] Use device password from config file
[7/30/2019, 4:01:28 PM] [DysonPlatform] undefined IP:undefined Serial Number:undefined
[7/30/2019, 4:01:28 PM] TypeError: Cannot read property 'match' of undefined
    at new DysonLinkDevice (/usr/local/lib/node_modules/homebridge-dyson-link/DysonLinkDevice.js:20:42)
    at config.accessories.forEach (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:82:42)
    at Array.forEach (<anonymous>)
    at getDevicesFromAccount (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:50:49)
    at IncomingMessage.res.on (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:213:25)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[7/30/2019, 4:01:29 PM] Got SIGTERM, shutting down Homebridge...

Here is my json

 "platform": "DysonPlatform",
            "name": "DysonPlatform",
            "email": "my@email.com",
            "password": "accountpassord",
            "country": "US",
            "accessories": [
                {
                    "ip": "10.0.1.161",
                    "displayName": "Dyson",
                    "serialNumber": "NM7-US-XXXXXX",
                    "password": "unitpassword"
                },

**Comment by ifeign** [comment] 2019-08-07 02:32
Duplicate of https://github.com/joe-ng/homebridge-dyson-link/issues/88

**Closed** 2019-09-26 08:30 UTC
